server:
  port: 4090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/czp?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    #    Redis服务器地址
#    host: 192.168.102.100
    host: 127.0.0.1
    #    端口号
    port: 6379

  #邮箱验证码配置
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com;163邮箱是smtp.163.com
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 470565129@qq.com
    #授权码
    password: gihqwkpaaijnbgfc
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

file:
  avatar:
    base: E:\\ProgrammingSoftware\\apache-tomcat-10.0.12\\webapps\\czp\\avatar\\
    serve: http://localhost:8088/czp/avatar/

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

avatar:
  url: http://localhost:8088/upload/sepim/avatar/